### PR TITLE
Make memory.json config a parameter

### PR DESCRIPTION
**Pull request by j16sdiz**
Make memory.json path configurable

### CODE REVIEW

**Comment by j16sdiz** [comment]
We should be able to run multiple bots under the same user.

**Comment by endofline** [comment]
I like this idea, it can actually be expanded to multiple bot's sharing the same memory if concurrent file write issues can be resolved.

**Comment by endofline** [comment]
re: 76d9e503 in **staging** branch, will be committed and closed automatically when `staging` -> `master`

**Comment by endofline** [comment]
Just a note: the change has been merged into master via: cherrypick

**Pull request merged**
