### PR TITLE
Monitor adds config plugin

### PR DESCRIPTION
**Pull request by nh-99**
Operating similarly to the syncrooms_config plugin, this allows you to add moderators "on the fly" with no need to do any configuration in the .json file.

Usage:
`/bot addmod <user id>`
Add's a user to the moderator list with the user id <user id>

`/bot delmod <user id>`
Removes a user form the moderator list that has the user id <user id>

### CODE REVIEW

**Comment by endofline** [comment]
am considering integrating this into the monitoradds plugin itself  - any objections?

**Comment by nh-99** [comment]
None whatsoever, just updated

**Comment by endofline** [comment]
thanks, will merge this and update it so that it will work for the new framework as well :)

**Comment by endofline** [comment]
merged to **framework/2.4** - pr will close on master merge

**Pull request merged**
