### PR TITLE
memory implementation for bot

### PR DESCRIPTION
**Pull request by endofline**
* new utility functions for memory/config manipulation: `get_option`, `get_suboption`, exists
  * refactored `hangupsbot.py`:`get_config_option`, `get_config_suboption` to use new `config.py` utility functions
  * merged enhancement branch (d301ecd) + refactored: `get_memory_option`, `get_memory_suboption`
* implemented memory.json:
  * as a cache for remembering previous 1-to-1 conversations (a94f25e)
  * nicknames, label (first name + nickname)
  * call `hangupsbot.py`:`initialise_user_memory(chat_id)` before any check on stored values to ensure that the data store is properly initialised
* @mentions
  * added nickname support - must be exact match (ce7aab8)
  * allow usage of underscore for full name matches like "AB_Chin" (ce7aab8)
  * refactored user searching to deny multiple recipients if the @mention is too vague, initiating user will be warned by bot and shown all matched names (0a74330)

### CODE REVIEW

**Comment by endofline** [comment]
added bugfixes, one related to no nicknames being set

**Comment by endofline** [comment]
bugfix: exceptions being thrown when no 1-on-1 found for a user, the bot was not checking whether a conversation was actually found

**Comment by endofline** [comment]
* bugfix: commit c8f6b4c has been reverted
* mentionquidproquo no longer determines whether users receive a warning message when attempting to message multiple users

**Comment by endofline** [comment]
documentation added for @mentions usage + debugging the bot in light of recent difficulties

**Comment by nylonee** [comment]
Looks good to me, tests are looking good.

**Pull request merged**
